services:
  - name: news-surge-worker
    type: worker
    runtime: docker
    plan: starter
    region: oregon
    autoDeploy: true

    # persistent SQLite storage
    disk:
      name: db
      mountPath: /data
      sizeGB: 1

    envVars:
      # --- News / Data Providers ---
      - key: MARKETAUX_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false

      # choose one realtime source; you can set both
      - key: POLYGON_API_KEY
        sync: false
      - key: ALPACA_KEY_ID
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false

      # Discord notifications
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false

      # --- Storage ---
      - key: DB_PATH
        value: /data/events.db

      # --- Polling cadence ---
      - key: POLL_NEWS_SECONDS
        value: "15"
      - key: NEWS_LOOKBACK_MINUTES
        value: "60"

      # --- Scoring/Confirmation thresholds ---
      - key: ALERT_THRESHOLD
        value: "0.72"
      - key: VOL_Z_MIN
        value: "3"
      - key: RET_1M_MIN
        value: "0.05"
      - key: VWAP_DEV_MIN
        value: "0.02"
      - key: VOL_WINDOW_SIZE
        value: "60"

      # Optional (uncomment if your code reads them)
      # - key: RISK_PCT
      #   value: "0.01"
      # - key: STARTING_EQUITY
      #   value: "100000"
